/**
 * Parsers for runtime stash dumps.
 *
 * Two formats. JSON is preferred: it states list-ness directly and keeps keys
 * that happen to be numeric distinct from array indices.
 *
 * The ASCII tree is accepted because it is what the Perl side already produces.
 * It has no list syntax, but Perl's array indices survive it as the keys `0`,
 * `1`, `2`, so lists are recoverable — see `collapseIndexedHashes`. The
 * recovery is a heuristic, which is why JSON remains preferred: a hash whose
 * keys genuinely are `0`, `1`, `2` is indistinguishable from an array.
 */
import { ensurePath, merge, node, type SchemaNode } from "./model";
import { safeValue } from "./redact";

/** Indent width of one level in the ASCII tree format. */
const INDENT = 3;

/** A branch with no members: `form =  (no elements)`. */
const EMPTY_MARKER = "(no elements)";

/**
 * Parses the ASCII tree produced by the Perl side.
 *
 * ```
 * ir
 * |- config
 * |  |- company
 * |  |  `- coy_id = 1234
 * `- var
 * ```
 *
 * Tolerant by design: a malformed line is skipped rather than aborting the
 * file, because a dump is generated by someone else's code and half a schema
 * beats none.
 */
/**
 * Rewrites hashes whose keys are exactly `0..n-1` into lists.
 *
 * The ASCII format has no list syntax, but Perl's array indices survive it as
 * numeric keys, so an array arrives looking like `{0: {...}, 1: {...}}`. The
 * consecutive-from-zero test is what separates those from a genuinely
 * numeric-keyed hash: this dump also contains year maps like `2025 = 1`, which
 * must stay hashes.
 *
 * Element shapes are the union of the items, because real data is ragged.
 */
function collapseIndexedHashes(n: SchemaNode): void {
  for (const child of n.children.values()) collapseIndexedHashes(child);
  if (n.element) collapseIndexedHashes(n.element);

  const keys = [...n.children.keys()];
  if (keys.length < 1) return;
  if (!keys.every((k) => /^\d+$/.test(k))) return;

  const indices = keys.map(Number).sort((a, b) => a - b);
  const consecutiveFromZero = indices.every((v, i) => v === i);
  if (!consecutiveFromZero) return;

  const element = node("hash", "dump");
  for (const child of n.children.values()) merge(element, child);
  n.kind = "list";
  n.element = element;
  n.children.clear();
}

export function parseAsciiDump(text: string): SchemaNode {
  const root = node("hash", "dump");
  // Stack of the node at each depth; index 0 is the dump's own root line.
  const stack: SchemaNode[] = [root];

  for (const rawLine of text.split("\n")) {
    if (!rawLine.trim()) continue;

    const prefix = /^[ |`\-]*/.exec(rawLine)?.[0] ?? "";
    const body = rawLine.slice(prefix.length);
    if (!body) continue;

    // The root line has no connector; children are indented in units of three.
    const depth = prefix.length === 0 ? 0 : Math.floor(prefix.length / INDENT);

    const eq = body.indexOf(" = ");
    const name = (eq === -1 ? body : body.slice(0, eq)).trim();
    if (!name) continue;

    const rawValue = eq === -1 ? undefined : body.slice(eq + 3).trim();

    // A key is a single identifier-ish token. Rejecting anything else stops a
    // junk line from being adopted as a new root and orphaning the siblings
    // that follow it.
    if (!/^[A-Za-z0-9_][\w.:@+-]*$/.test(name)) continue;

    let current: SchemaNode;
    if (rawValue === undefined || rawValue === "" || rawValue === EMPTY_MARKER) {
      current = node(rawValue === undefined ? "unknown" : "hash", "dump");
    } else {
      current = node("scalar", "dump");
      if (rawValue !== "undef") {
        const safe = safeValue(name, rawValue);
        current.value = safe.value;
        current.redacted = safe.redacted;
      }
    }

    const parent = stack[depth];
    if (depth === 0) {
      // The dump's root line names the variable it dumped, e.g. `ir`.
      root.children.set(name, current);
      stack.length = 1;
      stack[1] = current;
      if (current.kind === "unknown") current.kind = "hash";
      continue;
    }
    if (!parent) continue;

    if (current.kind === "unknown") current.kind = "hash";
    if (parent.kind === "unknown") parent.kind = "hash";
    parent.children.set(name, current);
    stack.length = depth + 1;
    stack[depth + 1] = current;
  }

  collapseIndexedHashes(root);
  return root;
}

/**
 * Builds a schema from a JSON dump.
 *
 * A list contributes the *union* of its items' shapes. Real data is ragged —
 * one director has a description and the next does not — and offering the union
 * is more useful than offering whatever the first item happened to carry.
 */
export function parseJsonDump(text: string): SchemaNode {
  let data: unknown;
  try {
    data = JSON.parse(text);
  } catch {
    return node("hash", "dump");
  }
  const root = fromValue(data, "");
  if (root.kind !== "hash") {
    const wrapper = node("hash", "dump");
    return wrapper;
  }
  return root;
}

function fromValue(value: unknown, key: string): SchemaNode {
  if (Array.isArray(value)) {
    const list = node("list", "dump");
    const element = node("hash", "dump");
    for (const item of value) merge(element, fromValue(item, key));
    list.element = element;
    return list;
  }

  if (value !== null && typeof value === "object") {
    const hash = node("hash", "dump");
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      hash.children.set(k, fromValue(v, k));
    }
    return hash;
  }

  const scalar = node("scalar", "dump");
  if (value !== null && value !== undefined) {
    const safe = safeValue(key, String(value));
    scalar.value = safe.value;
    scalar.redacted = safe.redacted;
  }
  return scalar;
}

/** Chooses a parser by content: JSON if it looks like JSON, else ASCII tree. */
export function parseDump(text: string): SchemaNode {
  const head = text.trimStart()[0];
  return head === "{" || head === "[" ? parseJsonDump(text) : parseAsciiDump(text);
}

/** Curated schema files declare descriptions and types alongside structure. */
export interface CuratedEntry {
  description?: string;
  type?: string;
  children?: Record<string, CuratedEntry>;
}

/**
 * Reads a curated schema: a JSON object mapping dotted paths to metadata.
 *
 * ```json
 * { "global.is_en": { "type": "boolean", "description": "English edition." } }
 * ```
 */
export function parseCurated(text: string): SchemaNode {
  const root = node("hash", "curated");
  let data: unknown;
  try {
    data = JSON.parse(text);
  } catch {
    return root;
  }
  if (!data || typeof data !== "object" || Array.isArray(data)) return root;

  for (const [path, raw] of Object.entries(data as Record<string, unknown>)) {
    if (!raw || typeof raw !== "object") continue;
    const entry = raw as CuratedEntry;
    const segments = path.split(".").filter(Boolean);
    if (!segments.length) continue;

    const leaf = ensurePath(root, segments, "curated");
    leaf.source = "curated";
    if (typeof entry.description === "string") leaf.description = entry.description;
    if (typeof entry.type === "string") {
      leaf.type = entry.type;
      if (entry.type === "list" || entry.type === "array") leaf.kind = "list";
      else if (entry.type === "hash" || entry.type === "object") leaf.kind = "hash";
      else if (leaf.kind === "unknown") leaf.kind = "scalar";
    }
  }

  return root;
}
